name: Deploy Backend to NHN Cloud

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'docker-compose-external-mysql.yml'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Backend Docker Image
        working-directory: ./backend
        run: docker build -t quiz-backend:latest .

      - name: Save Docker Image
        run: docker save quiz-backend:latest | gzip > quiz-backend.tar.gz

      - name: Copy Docker Image to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "quiz-backend.tar.gz"
          target: "~/"

      - name: Copy docker-compose file to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose-external-mysql.yml,.env.example"
          target: "~/simple-quiz-app/"
          strip_components: 0

      - name: Deploy on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/simple-quiz-app

            # Docker 이미지 로드
            docker load < ~/quiz-backend.tar.gz
            rm ~/quiz-backend.tar.gz

            # .env 파일 생성 (처음 한 번만)
            if [ ! -f .env ]; then
              cp .env.example .env
              echo "⚠️  .env 파일을 직접 수정해주세요!"
            fi

            # 백엔드 컨테이너 재시작
            docker-compose -f docker-compose-external-mysql.yml stop backend
            docker-compose -f docker-compose-external-mysql.yml rm -f backend
            docker-compose -f docker-compose-external-mysql.yml up -d backend

            # 로그 확인
            docker-compose -f docker-compose-external-mysql.yml logs --tail=50 backend
