name: Deploy Backend to KT Cloud

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'docker-compose-external-mysql.yml'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Backend Docker Image
        working-directory: ./backend
        run: docker build -t quiz-backend:latest .

      - name: Save Docker Image
        run: docker save quiz-backend:latest | gzip > quiz-backend.tar.gz

      - name: Copy Docker Image to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.KT_SERVER_HOST }}
          username: ${{ secrets.KT_SERVER_USER }}
          port: ${{ secrets.KT_SSH_PORT }}
          password: ${{ secrets.KT_SERVER_PASSWORD }}
          source: "quiz-backend.tar.gz"
          target: "~/"

      - name: Copy backend source to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.KT_SERVER_HOST }}
          username: ${{ secrets.KT_SERVER_USER }}
          port: ${{ secrets.KT_SSH_PORT }}
          password: ${{ secrets.KT_SERVER_PASSWORD }}
          source: "backend/**"
          target: "~/simple-quiz-app/"
          strip_components: 0

      - name: Copy docker-compose file to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.KT_SERVER_HOST }}
          username: ${{ secrets.KT_SERVER_USER }}
          port: ${{ secrets.KT_SSH_PORT }}
          password: ${{ secrets.KT_SERVER_PASSWORD }}
          source: "docker-compose-external-mysql.yml"
          target: "~/simple-quiz-app/"
          strip_components: 0

      - name: Deploy on KT Cloud Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.KT_SERVER_HOST }}
          username: ${{ secrets.KT_SERVER_USER }}
          port: ${{ secrets.KT_SSH_PORT }}
          password: ${{ secrets.KT_SERVER_PASSWORD }}
          envs: DB_HOST,DB_PORT,DB_NAME,DB_USERNAME,DB_PASSWORD,BACKEND_PORT,FRONTEND_PORT
          script: |
            cd ~/simple-quiz-app

            # .env 파일 생성
            cat > .env << EOF
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            BACKEND_PORT=${{ secrets.BACKEND_PORT }}
            FRONTEND_PORT=${{ secrets.FRONTEND_PORT }}
            EOF

            # Docker 이미지 로드
            docker load < ~/quiz-backend.tar.gz
            rm ~/quiz-backend.tar.gz

            # 백엔드 컨테이너 재시작
            docker compose -f docker-compose-external-mysql.yml stop backend
            docker compose -f docker-compose-external-mysql.yml rm -f backend
            docker compose -f docker-compose-external-mysql.yml up -d backend

            # 잠시 대기
            sleep 10

            # 로그 확인
            docker compose -f docker-compose-external-mysql.yml logs --tail=50 backend

            # 상태 확인
            docker ps | grep quiz-backend
